b= input("digite algo: ")
print("o tipo primitivo desse valor é: ", type(b))
print("só tem espaço? ", b.isspace())
print('é um numero? ', b.isnumeric())
print('é alfabetico? ', b.isalpha())
print(' é alfanumerico? ', b.isalnum())
print('esta em maiuxculas? ', b.isupper())
print('esta minuscula? ', b.islower())
print('esta capitalizada? ', b.istitle())